apiVersion: v1
kind: Pod
metadata:
        name: doscont
spec:
        containers:
                - name: cont1
                  image: python:3.9
                  #command: ['sh', '-C', 'python -m http.server 8081']
                  #- name: cont2
                  #image: python:3.6-alpine
                  #command: ['sh', '-C', 'echo cont2 >> index.html']
  

