apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: backend
        image: k8s-practicas 
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: backend-k8s
  labels:
          app: back
spec:      
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

